# Regression Dataset Preparation

This notebook prepares the combined dataset for regression analysis by merging all commercial bank CSV files into a single dataset.

**Purpose:** Create a unified dataset from individual bank stock data files for training regression models.

**Output:** `combined_banks_dataset.csv` - A merged dataset containing all commercial bank stock data.

## 1. Import Required Libraries

Import necessary Python libraries for data manipulation and file operations.

In [11]:
import pandas as pd
import glob
import os

print("Libraries imported successfully!")

Libraries imported successfully!

## 2. Locate Commercial Bank Data Files

Identify all CSV files in the commercial-banks directory containing individual bank stock data.

In [12]:
# Define data directory
DATA_DIR = "commercial-banks/"

# Find all CSV files
csv_files = glob.glob(os.path.join(DATA_DIR, "*.csv"))

print(f"Found {len(csv_files)} bank CSV files:")
for file in csv_files:
    bank_name = os.path.basename(file)
    print(f"  - {bank_name}")

Found 17 bank CSV files:
  - SCB.csv
  - NICA.csv
  - PCBL.csv
  - PRVU.csv
  - EBL.csv
  - GBIME.csv
  - CZBIL.csv
  - KBL.csv
  - MBL.csv
  - HBL.csv
  - SBL.csv
  - SANIMA.csv
  - NABIL.csv
  - ADBL.csv
  - SBI.csv
  - NBL.csv
  - NMB.csv

## 3. Load and Process Individual Bank Data

Load each bank's CSV file and add a company identifier to distinguish between different banks.

In [13]:
print("Loading individual bank datasets...\n")

df_list = []

for file in csv_files:
    # Load CSV file
    df = pd.read_csv(file)
    
    # Extract company ID from filename
    company_id = os.path.basename(file).split('.')[0]
    
    # Add company identifier column
    df['company_id'] = company_id
    
    # Add to list
    df_list.append(df)
    
    print(f"  Loaded {company_id}: {len(df)} rows")

print(f"\nTotal dataframes loaded: {len(df_list)}")

Loading individual bank datasets...

  Loaded SCB: 3342 rows
  Loaded NICA: 2842 rows
  Loaded PCBL: 3342 rows
  Loaded PRVU: 2192 rows
  Loaded EBL: 3342 rows
  Loaded GBIME: 2598 rows
  Loaded CZBIL: 3742 rows
  Loaded KBL: 3150 rows
  Loaded MBL: 2992 rows
  Loaded HBL: 3077 rows
  Loaded SBL: 3192 rows
  Loaded SANIMA: 3142 rows
  Loaded NABIL: 3342 rows
  Loaded ADBL: 3492 rows
  Loaded SBI: 3342 rows
  Loaded NBL: 2942 rows
  Loaded NMB: 2992 rows

Total dataframes loaded: 17

## 4. Combine All Bank Data

Merge all individual bank dataframes into a single combined dataset.

In [14]:
# Concatenate all dataframes
data = pd.concat(df_list, ignore_index=True)

print(f"Combined dataset created with {len(data):,} total rows")
print(f"\nDataset shape: {data.shape}")
print(f"Columns: {list(data.columns)}")

Combined dataset created with 53,063 total rows

Dataset shape: (53063, 10)
Columns: ['published_date', 'open', 'high', 'low', 'close', 'per_change', 'traded_quantity', 'traded_amount', 'status', 'company_id']

## 5. Process Dates and Sort Data

Convert date column to datetime format and sort by company and date for chronological analysis.

In [15]:
# Convert published_date to datetime
data['published_date'] = pd.to_datetime(data['published_date'])

# Sort by company and date
data = data.sort_values(['company_id', 'published_date']).reset_index(drop=True)

print("Date conversion and sorting completed!")
print(f"\nDate range: {data['published_date'].min()} to {data['published_date'].max()}")
print(f"\nFirst few rows:")
display(data.head())

Date conversion and sorting completed!

Date range: 2009-06-25 00:00:00 to 2025-12-29 00:00:00

First few rows:

,published_date,open,high,low,close,per_change,traded_quantity,traded_amount,status,company_id
0,2010-09-16,117.0,122.0,116.0,120.0,NaN,5280.0,0.0,0,ADBL
1,2010-09-19,120.0,120.0,116.0,118.0,-1.67,2648.0,0.0,0,ADBL
2,2010-09-20,118.0,119.0,116.0,118.0,0.00,2346.0,0.0,0,ADBL
3,2010-09-21,118.0,118.0,115.0,116.0,-1.69,7160.0,0.0,0,ADBL
4,2010-09-23,116.0,120.0,117.0,120.0,3.45,8417.0,0.0,0,ADBL

## 6. Save Combined Dataset

Export the processed combined dataset to a CSV file for use in regression models.

In [16]:
# Save to CSV
output_file = "combined_banks_dataset.csv"
data.to_csv(output_file, index=False)

print("="*60)
print(f"Combined dataset saved: {output_file}")
print(f"  Total rows: {len(data):,}")
print(f"  Number of banks: {data['company_id'].nunique()}")
print(f"  Date range: {data['published_date'].min()} to {data['published_date'].max()}")
print(f"  Columns: {list(data.columns)}")
print("="*60)

============================================================
Combined dataset saved: combined_banks_dataset.csv
  Total rows: 53,063
  Number of banks: 17
  Date range: 2009-06-25 00:00:00 to 2025-12-29 00:00:00
  Columns: ['published_date', 'open', 'high', 'low', 'close', 'per_change', 'traded_quantity', 'traded_amount', 'status', 'company_id']
============================================================

## 7. Dataset Summary Statistics

Display descriptive statistics for numerical features in the combined dataset.

In [17]:
print("Dataset Summary Statistics:")
print("="*60)
display(data.describe())

Dataset Summary Statistics:
============================================================

,published_date,open,high,low,close,per_change,traded_quantity,traded_amount,status
count,53063,53063.000000,53063.000000,53063.000000,53063.000000,53046.000000,5.306300e+04,5.306300e+04,53063.000000
mean,2018-12-04 02:27:18.158415360,559.953382,567.179590,552.082047,559.515350,0.034534,4.876580e+04,1.978984e+07,-0.084353
min,2009-06-25 00:00:00,98.000000,100.000000,98.000000,98.000000,-72.740000,1.000000e+01,0.000000e+00,-1.000000
25%,2015-06-07 00:00:00,262.000000,266.000000,258.000000,261.000000,-0.970000,5.513500e+03,2.831650e+06,-1.000000
50%,2018-12-23 00:00:00,399.000000,404.000000,392.000000,398.000000,0.000000,1.778700e+04,7.640956e+06,0.000000
75%,2022-07-21 00:00:00,614.000000,620.000000,605.000000,612.875000,0.870000,5.140150e+04,1.940470e+07,0.000000
max,2025-12-29 00:00:00,3895.000000,3952.000000,3800.000000,3895.000000,130.340000,2.489844e+06,1.179786e+09,1.000000
std,NaN,510.813948,517.203253,505.048434,511.400241,2.362701,9.690847e+04,3.908727e+07,0.722001

## 8. Samples Per Bank

Analyze the distribution of data points across different banks to ensure balanced representation.

In [18]:
print("Number of samples per bank:")
print("="*60)

bank_counts = data.groupby('company_id').size().sort_values(ascending=False)
print(bank_counts)

print(f"\nAverage samples per bank: {bank_counts.mean():.0f}")
print(f"Median samples per bank: {bank_counts.median():.0f}")

Number of samples per bank:
============================================================
company_id
CZBIL     3742
ADBL      3492
NABIL     3342
SBI       3342
PCBL      3342
SCB       3342
EBL       3342
SBL       3192
KBL       3150
SANIMA    3142
HBL       3077
MBL       2992
NMB       2992
NBL       2942
NICA      2842
GBIME     2598
PRVU      2192
dtype: int64

Average samples per bank: 3121
Median samples per bank: 3150

## 9. Data Information

Display detailed information about the dataset including data types and missing values.

In [19]:
print("Dataset Information:")
print("="*60)
data.info()

print("\nMissing Values:")
print("="*60)
missing = data.isnull().sum()
if missing.sum() > 0:
    print(missing[missing > 0])
else:
    print("No missing values found!")

Dataset Information:
============================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53063 entries, 0 to 53062
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   published_date   53063 non-null  datetime64[ns]
 1   open             53063 non-null  float64
 2   high             53063 non-null  float64
 3   low              53063 non-null  float64
 4   close            53063 non-null  float64
 5   per_change       53046 non-null  float64
 6   traded_quantity  53063 non-null  float64
 7   traded_amount    53063 non-null  float64
 8   status           53063 non-null  int64
 9   company_id       53063 non-null  object
dtypes: datetime64[ns](1), float64(7), int64(1), object(1)
memory usage: 4.0+ MB

Missing Values:
============================================================
per_change    17
dtype: int64

## 10. Completion Summary

Final confirmation that the dataset is ready for regression model training.

In [20]:
print("\n" + "="*60)
print("DATASET PREPARATION COMPLETE")
print("="*60)
print(f"\nDataset: {output_file}")
print(f"Total Records: {len(data):,}")
print(f"Number of Banks: {data['company_id'].nunique()}")
print(f"Time Period: {data['published_date'].min().strftime('%Y-%m-%d')} to {data['published_date'].max().strftime('%Y-%m-%d')}")
print(f"\nReady for regression model training")
print("="*60)

============================================================
DATASET PREPARATION COMPLETE
============================================================

Dataset: combined_banks_dataset.csv
Total Records: 53,063
Number of Banks: 17
Time Period: 2009-06-25 to 2025-12-29

Ready for regression model training
============================================================